repos:
  - repo: https://github.com/godaddy/tartufo
    rev: "v5.0.2"
    hooks:
      - id: tartufo
        language_version: python3.13

  - repo: https://github.com/kxue43/shell-cmd-on-change
    rev: "2.0.0"
    hooks:
      - id: shell-cmd-on-change
        name: set-up
        args:
          - "-Pset-up.sh"
          - "~/.config/dot-files/set-up.sh"
        stages: [post-merge]
        always_run: true
        verbose: true
